path: $GRAPHNET/data/examples/sqlite/prometheus/prometheus-events.db
pulsemaps:
  - total
features:
  - sensor_pos_x
  - sensor_pos_y
  - sensor_pos_z
  - t
truth:
  - injection_energy
  - injection_type
  - injection_interaction_type
  - injection_zenith
  - injection_azimuth
  - injection_bjorkenx
  - injection_bjorkeny
  - injection_position_x
  - injection_position_y
  - injection_position_z
  - injection_column_depth
  - primary_lepton_1_type
  - primary_hadron_1_type
  - primary_lepton_1_position_x
  - primary_lepton_1_position_y
  - primary_lepton_1_position_z
  - primary_hadron_1_position_x
  - primary_hadron_1_position_y
  - primary_hadron_1_position_z
  - primary_lepton_1_direction_theta
  - primary_lepton_1_direction_phi
  - primary_hadron_1_direction_theta
  - primary_hadron_1_direction_phi
  - primary_lepton_1_energy
  - primary_hadron_1_energy
  - total_energy
  - dummy_pid
index_column: event_no
truth_table: mc_truth
seed: 21
selection:
  test_noise: 60 random events ~ event_no % 5 == 0 & (dummy_pid == 1 | dummy_pid == -1)
  test_nu_e: 60 random events ~ event_no % 5 == 0 & (dummy_pid == 12 | dummy_pid == -12)
  test_nu_mu: 60 random events ~ event_no % 5 == 0 & (dummy_pid == 14| dummy_pid == -14)
  test_nu_tau: 60 random events ~ event_no % 5 == 0 & (dummy_pid == 16 | dummy_pid == -16)
  test_mu: 60 random events ~ event_no % 5 == 0 & (dummy_pid == 13 | dummy_pid == -13)

  validation_noise: 60 random events ~ event_no % 5 == 1 & (dummy_pid == 1 | dummy_pid == -1)
  validation_nu_e: 60 random events ~ event_no % 5 == 1 & (dummy_pid == 12 | dummy_pid == -12)
  validation_nu_mu: 60 random events ~ event_no % 5 == 1 & (dummy_pid == 14 | dummy_pid == -14)
  validation_nu_tau: 60 random events ~ event_no % 5 == 1 & (dummy_pid == 16 | dummy_pid == -16)
  validation_mu: 60 random events ~ event_no % 5 == 1 & (dummy_pid == 13 | dummy_pid == -13)

  train_noise: 60 random events ~ event_no % 5 > 1 & (dummy_pid == 1 | dummy_pid == -1)
  train_nu_e: 60 random events ~ event_no % 5 > 1 & (dummy_pid == 12 | dummy_pid == -12)
  train_nu_mu: 60 random events ~ event_no % 5 > 1 & (dummy_pid == 14 | dummy_pid == -14)
  train_nu_tau: 60 random events ~ event_no % 5 > 1 & (dummy_pid == 16 | dummy_pid == -16)
  train_mu: 60 random events ~ event_no % 5 > 1 & (dummy_pid == 13 | dummy_pid == -13)