# This is a simple workflow to check that all modified files satisfy code
# quality requirements
name: Code quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push and PRs
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pre-commit:
    name: Pre-commit - ${{ matrix.hook }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hook: ["black", "flake8", "docformatter", "pydocstyle", "mypy"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package
        uses: ./.github/actions/install

      - name: Run ${{ matrix.hook }}
        run: |
          pip show ${{ matrix.hook }}
          pre-commit run ${{ matrix.hook }} --all-files
